// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transcendence.Data;

#nullable disable

namespace Transcendence.Service.Migrations
{
    [DbContext(typeof(TranscendenceContext))]
    [Migration("20260712202113_AddUserAccountLockout")]
    partial class AddUserAccountLockout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatchSummoner", b =>
                {
                    b.Property<Guid>("MatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SummonersId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchesId", "SummonersId");

                    b.HasIndex("SummonersId");

                    b.ToTable("MatchSummoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.AdminAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Action", "CreatedAtUtc");

                    b.HasIndex("ActorUserAccountId", "CreatedAtUtc");

                    b.ToTable("AdminAuditEvents");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.ApiClientKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("ApiClientKeys");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserFavoriteSummoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummonerPuuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "SummonerPuuid", "PlatformRegion")
                        .IsUnique();

                    b.ToTable("UserFavoriteSummoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserPreferences", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LivePollingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredRankTier")
                        .HasColumnType("text");

                    b.Property<string>("PreferredRegion")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserAccountId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "ExpiresAtUtc");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("text");

                    b.HasKey("UserAccountId", "Role");

                    b.HasIndex("Role");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LiveGame.LiveGameSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GameId")
                        .HasColumnType("text");

                    b.Property<DateTime>("NextPollAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NextPollAtUtc");

                    b.HasIndex("Puuid", "PlatformRegion", "ObservedAtUtc");

                    b.ToTable("LiveGameSnapshots");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.ChampionMastery", b =>
                {
                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionLevel")
                        .HasColumnType("integer");

                    b.Property<long>("ChampionPoints")
                        .HasColumnType("bigint");

                    b.Property<bool>("ChestGranted")
                        .HasColumnType("boolean");

                    b.Property<long>("LastPlayTime")
                        .HasColumnType("bigint");

                    b.Property<int>("TokensEarned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SummonerId", "ChampionId");

                    b.ToTable("ChampionMasteries");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.HistoricalRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId");

                    b.ToTable("HistoricalRanks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId", "QueueType")
                        .IsUnique();

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.RankedSeason", b =>
                {
                    b.Property<string>("SeasonKey")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SeasonKey");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartUtc", "EndUtc");

                    b.ToTable("RankedSeasons");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Summoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<string>("GameNameNormalized")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastActiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlatformRegion")
                        .HasColumnType("text");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<long>("RevisionDate")
                        .HasColumnType("bigint");

                    b.Property<string>("RiotSummonerId")
                        .HasColumnType("text");

                    b.Property<long>("SummonerLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("SummonerName")
                        .HasColumnType("text");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.Property<string>("TagLineNormalized")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.HasIndex("PlatformRegion", "UpdatedAt")
                        .HasDatabaseName("IX_Summoners_Region_UpdatedAt");

                    b.HasIndex("PlatformRegion", "GameNameNormalized", "TagLineNormalized")
                        .HasDatabaseName("IX_Summoners_SearchPrefix")
                        .HasFilter("\"GameNameNormalized\" IS NOT NULL AND \"TagLineNormalized\" IS NOT NULL");

                    b.HasIndex(new[] { "PlatformRegion", "UpdatedAt" }, "IX_Summoners_Region_UpdatedAt_Active")
                        .HasFilter("\"LastActiveAtUtc\" IS NOT NULL");

                    b.ToTable("Summoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerFullHistoryBackfill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CursorEndEpochSeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("DetailFetchFailures")
                        .HasColumnType("integer");

                    b.Property<int>("FactsPersisted")
                        .HasColumnType("integer");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("MatchIdsDiscovered")
                        .HasColumnType("integer");

                    b.Property<int>("PagesScanned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SkippedExistingFacts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.HasIndex("SummonerId", "Scope")
                        .IsUnique();

                    b.ToTable("SummonerFullHistoryBackfills");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerIngestionCursor", b =>
                {
                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("BackfillBeforeEpochSeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("ConsecutiveNoopRuns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("SummonerId", "Scope");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("SummonerIngestionCursors");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerMatchFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<bool>("CountsTowardRankedTotal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("EndOfGameResult")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("GameEndedInEarlySurrender")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GameEndedInSurrender")
                        .HasColumnType("boolean");

                    b.Property<string>("IndividualPosition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<long>("MatchDate")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("NeutralMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<string>("Patch")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PlatformRegion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QueueFamily")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RankedCountClassifierVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RankedCountExclusionReason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RegionalRoute")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SeasonKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SummonerSpell1Id")
                        .HasColumnType("integer");

                    b.Property<int>("SummonerSpell2Id")
                        .HasColumnType("integer");

                    b.Property<bool?>("TeamEarlySurrendered")
                        .HasColumnType("boolean");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamPosition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisionScore")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate", "QueueId");

                    b.HasIndex("SummonerId", "MatchId")
                        .IsUnique();

                    b.HasIndex("SummonerId", "SeasonKey", "QueueFamily");

                    b.HasIndex("SummonerId", "SeasonKey", "QueueId", "CountsTowardRankedTotal");

                    b.ToTable("SummonerMatchFacts");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerMatchFactFetchFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PlatformRegion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RegionalRoute")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedAtUtc", "LastAttemptAtUtc");

                    b.HasIndex("SummonerId", "MatchId")
                        .IsUnique();

                    b.ToTable("SummonerMatchFactFetchFailures");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerSeasonChampionStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AggregationVersion")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueScope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SeasonKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalAssists")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalCs")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDamageToChamps")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDeaths")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalKills")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalVisionScore")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId", "SeasonKey", "QueueScope", "ChampionId")
                        .IsUnique();

                    b.HasIndex("SummonerId", "SeasonKey", "QueueScope", "Games")
                        .HasDatabaseName("IX_SummonerSeasonChampionStats_SummonerId_SeasonKey_QueueScop~1");

                    b.ToTable("SummonerSeasonChampionStats");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerSeasonCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackfillStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ClassifierVersion")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedMatchCount")
                        .HasColumnType("integer");

                    b.Property<string>("CoverageStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastBackfilledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastComparedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QueueScope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("RankedCountDelta")
                        .HasColumnType("integer");

                    b.Property<int?>("RiotLosses")
                        .HasColumnType("integer");

                    b.Property<int?>("RiotTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("RiotWins")
                        .HasColumnType("integer");

                    b.Property<string>("SeasonKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId", "SeasonKey", "QueueScope")
                        .IsUnique();

                    b.ToTable("SummonerSeasonCoverages");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerSeasonOverviewStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AggregationVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueScope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SeasonKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalAssists")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalCs")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDamageToChamps")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDeaths")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalKills")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.Property<long>("TotalVisionScore")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId", "SeasonKey", "QueueScope")
                        .IsUnique();

                    b.ToTable("SummonerSeasonOverviewStats");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.TrackedProSummoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHighEloOtp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPro")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProName")
                        .HasColumnType("text");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("Puuid", "PlatformRegion")
                        .IsUnique();

                    b.ToTable("TrackedProSummoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Analytics.AnalyticsResponseSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Feature", "ScopeKey", "Patch")
                        .IsUnique();

                    b.ToTable("AnalyticsResponseSnapshots");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Analytics.ChampionBanScopeStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BannedMatches")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Patch", "PlatformRegion", "RankScope", "ChampionId")
                        .IsUnique();

                    b.ToTable("ChampionBanScopeStats");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Analytics.ChampionBuildSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Patch", "ChampionId", "Role", "RankScope")
                        .IsUnique();

                    b.ToTable("ChampionBuildSnapshots");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Analytics.ChampionMatchupStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LatestTimelineAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpponentChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SumGoldDiffAt15")
                        .HasColumnType("bigint");

                    b.Property<long>("SumXpDiffAt15")
                        .HasColumnType("bigint");

                    b.Property<int>("TimelineGames")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Patch", "ChampionId", "Role");

                    b.HasIndex("Patch", "RankTier", "ChampionId", "Role", "OpponentChampionId")
                        .IsUnique();

                    b.ToTable("ChampionMatchupStats");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Analytics.ChampionRoleTierStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Patch", "ChampionId", "Role");

                    b.HasIndex("Patch", "Role", "RankTier");

                    b.HasIndex("Patch", "PlatformRegion", "RankTier", "ChampionId", "Role")
                        .IsUnique();

                    b.ToTable("ChampionRoleTierStats");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Analytics.ChampionScopeGradeStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BanRate")
                        .HasColumnType("double precision");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ContestedScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLowSample")
                        .HasColumnType("boolean");

                    b.Property<int?>("Movement")
                        .HasColumnType("integer");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PickRate")
                        .HasColumnType("double precision");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PreviousTier")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PriorStrength")
                        .HasColumnType("double precision");

                    b.Property<string>("RankScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RoleBaseline")
                        .HasColumnType("double precision");

                    b.Property<double>("StrengthScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<double>("WinRate")
                        .HasColumnType("double precision");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Patch", "PlatformRegion", "RankScope", "Role");

                    b.HasIndex("Patch", "PlatformRegion", "RankScope", "Role", "ChampionId")
                        .IsUnique();

                    b.ToTable("ChampionScopeGradeStats");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Analytics.ScopeMatchCountStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Patch", "PlatformRegion", "RankScope")
                        .IsUnique();

                    b.ToTable("ScopeMatchCountStats");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("EndOfGameResult")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("MatchDate")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .HasColumnType("text");

                    b.Property<string>("QueueFamily")
                        .HasColumnType("text");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("QueueFamily");

                    b.HasIndex("QueueId");

                    b.HasIndex("QueueType");

                    b.HasIndex("PlatformRegion", "Status", "Patch");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchBan", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PickTurn")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "TeamId", "PickTurn", "ChampionId");

                    b.HasIndex("ChampionId");

                    b.HasIndex("ChampionId", "MatchId");

                    b.ToTable("MatchBans");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<bool?>("GameEndedInEarlySurrender")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GameEndedInSurrender")
                        .HasColumnType("boolean");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("MagicDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("NeutralMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PhysicalDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SummonerSpell1Id")
                        .HasColumnType("integer");

                    b.Property<int>("SummonerSpell2Id")
                        .HasColumnType("integer");

                    b.Property<bool?>("TeamEarlySurrendered")
                        .HasColumnType("boolean");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamPosition")
                        .HasColumnType("text");

                    b.Property<int>("TotalDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("TrueDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("VisionScore")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId");

                    b.HasIndex("MatchId", "ParticipantId");

                    b.HasIndex("MatchId", "SummonerId")
                        .IsUnique();

                    b.HasIndex(new[] { "ChampionId" }, "IX_MatchParticipants_ChampionId_Covering");

                    b.HasIndex(new[] { "ChampionId", "TeamPosition" }, "IX_MatchParticipants_ChampionId_TeamPosition_Covering");

                    b.HasIndex(new[] { "MatchId" }, "IX_MatchParticipants_MatchId_Covering");

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItem", b =>
                {
                    b.Property<Guid>("MatchParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MatchParticipantId", "SlotIndex");

                    b.HasIndex("ItemId", "PatchVersion");

                    b.HasIndex("MatchParticipantId", "ItemId");

                    b.ToTable("MatchParticipantItems");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItemPurchase", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("TimestampMs")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "ParticipantId", "PurchaseIndex");

                    b.ToTable("MatchParticipantItemPurchases");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantRune", b =>
                {
                    b.Property<Guid>("MatchParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("SelectionTree")
                        .HasColumnType("integer");

                    b.Property<int>("SelectionIndex")
                        .HasColumnType("integer");

                    b.Property<int>("RuneId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.HasKey("MatchParticipantId", "SelectionTree", "SelectionIndex", "RuneId");

                    b.HasIndex("RuneId", "PatchVersion");

                    b.ToTable("MatchParticipantRunes");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantSkillOrder", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstThree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sequence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MatchId", "ParticipantId");

                    b.ToTable("MatchParticipantSkillOrders");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantTimelineSnapshot", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("MinuteMark")
                        .HasColumnType("integer");

                    b.Property<int>("Cs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DerivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FrameTimestampMs")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("QualityFlags")
                        .HasColumnType("text");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "ParticipantId", "MinuteMark");

                    b.HasIndex("MinuteMark", "MatchId");

                    b.HasIndex(new[] { "MatchId", "ParticipantId", "MinuteMark" }, "IX_MatchParticipantTimelineSnapshots_Matchup");

                    b.ToTable("MatchParticipantTimelineSnapshots");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchTeamObjective", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("BaronFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("BaronKills")
                        .HasColumnType("integer");

                    b.Property<bool>("DragonFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("DragonKills")
                        .HasColumnType("integer");

                    b.Property<bool>("FirstBlood")
                        .HasColumnType("boolean");

                    b.Property<bool>("HordeFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("HordeKills")
                        .HasColumnType("integer");

                    b.Property<bool>("InhibitorFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("InhibitorKills")
                        .HasColumnType("integer");

                    b.Property<bool>("RiftHeraldFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("RiftHeraldKills")
                        .HasColumnType("integer");

                    b.Property<bool>("TowerFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("TowerKills")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "TeamId");

                    b.ToTable("MatchTeamObjectives");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchTimelineFetchState", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SourcePatch")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("MatchId");

                    b.HasIndex("LastAttemptAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("MatchTimelineFetchStates");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.ItemVersion", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("BuildsFrom")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("'{}'::integer[]");

                    b.PrimitiveCollection<List<int>>("BuildsInto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("'{}'::integer[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InStore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("ItemId", "PatchVersion");

                    b.HasIndex("PatchVersion");

                    b.ToTable("ItemVersions");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.Patch", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Version");

                    b.ToTable("Patches");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.RuneVersion", b =>
                {
                    b.Property<int>("RuneId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RunePathId")
                        .HasColumnType("integer");

                    b.Property<string>("RunePathName")
                        .HasColumnType("text");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("RuneId", "PatchVersion");

                    b.HasIndex("PatchVersion");

                    b.ToTable("RuneVersions");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentChampionLoadout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CurrentChampionLoadouts");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentDataParameters", b =>
                {
                    b.Property<Guid>("CurrentDataParametersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CurrentDataParametersId");

                    b.ToTable("CurrentDataParameters");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.Helpers.UnitWinPercent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CurrentChampionLoadoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfGames")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("WinRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CurrentChampionLoadoutId");

                    b.ToTable("UnitWinPercent");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.RefreshLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OwnerToken")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("LockedUntilUtc");

                    b.ToTable("RefreshLocks");
                });

            modelBuilder.Entity("MatchSummoner", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", null)
                        .WithMany()
                        .HasForeignKey("SummonersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserFavoriteSummoner", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Auth.UserAccount", "UserAccount")
                        .WithMany("FavoriteSummoners")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserPreferences", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Auth.UserAccount", "UserAccount")
                        .WithOne("Preferences")
                        .HasForeignKey("Transcendence.Data.Models.Auth.UserPreferences", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserRefreshToken", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Auth.UserAccount", "UserAccount")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserRole", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Auth.UserAccount", "UserAccount")
                        .WithMany("Roles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.ChampionMastery", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("ChampionMasteries")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.HistoricalRank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("HistoricalRanks")
                        .HasForeignKey("SummonerId");

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Rank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("Ranks")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerFullHistoryBackfill", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("FullHistoryBackfills")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerIngestionCursor", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("IngestionCursors")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerMatchFact", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("MatchFacts")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerMatchFactFetchFailure", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany()
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerSeasonChampionStat", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("SeasonChampionStats")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerSeasonCoverage", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("SeasonCoverages")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerSeasonOverviewStat", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("SeasonOverviewStats")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchBan", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("Bans")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipant", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItem", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.MatchParticipant", "MatchParticipant")
                        .WithMany("Items")
                        .HasForeignKey("MatchParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Static.ItemVersion", "ItemVersion")
                        .WithMany()
                        .HasForeignKey("ItemId", "PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemVersion");

                    b.Navigation("MatchParticipant");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItemPurchase", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantRune", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.MatchParticipant", "MatchParticipant")
                        .WithMany("Runes")
                        .HasForeignKey("MatchParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Static.RuneVersion", "RuneVersion")
                        .WithMany()
                        .HasForeignKey("RuneId", "PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchParticipant");

                    b.Navigation("RuneVersion");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantSkillOrder", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantTimelineSnapshot", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("TimelineSnapshots")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchTeamObjective", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("TeamObjectives")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchTimelineFetchState", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithOne("TimelineFetchState")
                        .HasForeignKey("Transcendence.Data.Models.LoL.Match.MatchTimelineFetchState", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.ItemVersion", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Static.Patch", "Patch")
                        .WithMany()
                        .HasForeignKey("PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patch");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.RuneVersion", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Static.Patch", "Patch")
                        .WithMany()
                        .HasForeignKey("PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patch");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.Helpers.UnitWinPercent", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Service.CurrentChampionLoadout", null)
                        .WithMany("UnitWinPercents")
                        .HasForeignKey("CurrentChampionLoadoutId");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserAccount", b =>
                {
                    b.Navigation("FavoriteSummoners");

                    b.Navigation("Preferences");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Summoner", b =>
                {
                    b.Navigation("ChampionMasteries");

                    b.Navigation("FullHistoryBackfills");

                    b.Navigation("HistoricalRanks");

                    b.Navigation("IngestionCursors");

                    b.Navigation("MatchFacts");

                    b.Navigation("MatchParticipants");

                    b.Navigation("Ranks");

                    b.Navigation("SeasonChampionStats");

                    b.Navigation("SeasonCoverages");

                    b.Navigation("SeasonOverviewStats");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.Match", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Participants");

                    b.Navigation("TeamObjectives");

                    b.Navigation("TimelineFetchState");

                    b.Navigation("TimelineSnapshots");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipant", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Runes");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentChampionLoadout", b =>
                {
                    b.Navigation("UnitWinPercents");
                });
#pragma warning restore 612, 618
        }
    }
}
