// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transcendence.Data;

#nullable disable

namespace Transcendence.Service.Migrations
{
    [DbContext(typeof(TranscendenceContext))]
    [Migration("20260609093624_AddOrderedBuildPurchasesAndSkillOrders")]
    partial class AddOrderedBuildPurchasesAndSkillOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatchSummoner", b =>
                {
                    b.Property<Guid>("MatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SummonersId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchesId", "SummonersId");

                    b.HasIndex("SummonersId");

                    b.ToTable("MatchSummoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.AdminAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Action", "CreatedAtUtc");

                    b.HasIndex("ActorUserAccountId", "CreatedAtUtc");

                    b.ToTable("AdminAuditEvents");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.ApiClientKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("ApiClientKeys");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserFavoriteSummoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummonerPuuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "SummonerPuuid", "PlatformRegion")
                        .IsUnique();

                    b.ToTable("UserFavoriteSummoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserPreferences", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LivePollingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredRankTier")
                        .HasColumnType("text");

                    b.Property<string>("PreferredRegion")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserAccountId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "ExpiresAtUtc");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("text");

                    b.HasKey("UserAccountId", "Role");

                    b.HasIndex("Role");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LiveGame.LiveGameSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GameId")
                        .HasColumnType("text");

                    b.Property<DateTime>("NextPollAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NextPollAtUtc");

                    b.HasIndex("Puuid", "PlatformRegion", "ObservedAtUtc");

                    b.ToTable("LiveGameSnapshots");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.ChampionMastery", b =>
                {
                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionLevel")
                        .HasColumnType("integer");

                    b.Property<long>("ChampionPoints")
                        .HasColumnType("bigint");

                    b.Property<bool>("ChestGranted")
                        .HasColumnType("boolean");

                    b.Property<long>("LastPlayTime")
                        .HasColumnType("bigint");

                    b.Property<int>("TokensEarned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SummonerId", "ChampionId");

                    b.ToTable("ChampionMasteries");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.HistoricalRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId");

                    b.ToTable("HistoricalRanks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId", "QueueType")
                        .IsUnique();

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Summoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<string>("GameNameNormalized")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .HasColumnType("text");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<long>("RevisionDate")
                        .HasColumnType("bigint");

                    b.Property<string>("RiotSummonerId")
                        .HasColumnType("text");

                    b.Property<long>("SummonerLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("SummonerName")
                        .HasColumnType("text");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.Property<string>("TagLineNormalized")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.HasIndex("PlatformRegion", "GameNameNormalized", "TagLineNormalized")
                        .HasDatabaseName("IX_Summoners_SearchPrefix")
                        .HasFilter("\"GameNameNormalized\" IS NOT NULL AND \"TagLineNormalized\" IS NOT NULL");

                    b.ToTable("Summoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerIngestionCursor", b =>
                {
                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("BackfillBeforeEpochSeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("ConsecutiveNoopRuns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("SummonerId", "Scope");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("SummonerIngestionCursors");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.TrackedProSummoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHighEloOtp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPro")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProName")
                        .HasColumnType("text");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("Puuid", "PlatformRegion")
                        .IsUnique();

                    b.ToTable("TrackedProSummoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("EndOfGameResult")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("MatchDate")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .HasColumnType("text");

                    b.Property<string>("QueueFamily")
                        .HasColumnType("text");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("QueueFamily");

                    b.HasIndex("QueueId");

                    b.HasIndex("QueueType");

                    b.HasIndex("PlatformRegion", "Status", "Patch");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchBan", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PickTurn")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "TeamId", "PickTurn", "ChampionId");

                    b.HasIndex("ChampionId");

                    b.HasIndex("ChampionId", "MatchId");

                    b.ToTable("MatchBans");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("MagicDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("NeutralMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PhysicalDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SummonerSpell1Id")
                        .HasColumnType("integer");

                    b.Property<int>("SummonerSpell2Id")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamPosition")
                        .HasColumnType("text");

                    b.Property<int>("TotalDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("TrueDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("VisionScore")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("MatchId");

                    b.HasIndex("SummonerId");

                    b.HasIndex("ChampionId", "TeamPosition");

                    b.HasIndex("MatchId", "ParticipantId");

                    b.HasIndex("MatchId", "SummonerId")
                        .IsUnique();

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItem", b =>
                {
                    b.Property<Guid>("MatchParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MatchParticipantId", "SlotIndex");

                    b.HasIndex("ItemId", "PatchVersion");

                    b.HasIndex("MatchParticipantId", "ItemId");

                    b.ToTable("MatchParticipantItems");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItemPurchase", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("TimestampMs")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "ParticipantId", "PurchaseIndex");

                    b.ToTable("MatchParticipantItemPurchases");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantRune", b =>
                {
                    b.Property<Guid>("MatchParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("SelectionTree")
                        .HasColumnType("integer");

                    b.Property<int>("SelectionIndex")
                        .HasColumnType("integer");

                    b.Property<int>("RuneId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.HasKey("MatchParticipantId", "SelectionTree", "SelectionIndex", "RuneId");

                    b.HasIndex("RuneId", "PatchVersion");

                    b.ToTable("MatchParticipantRunes");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantSkillOrder", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstThree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sequence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MatchId", "ParticipantId");

                    b.ToTable("MatchParticipantSkillOrders");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantTimelineSnapshot", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("MinuteMark")
                        .HasColumnType("integer");

                    b.Property<int>("Cs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DerivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FrameTimestampMs")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("QualityFlags")
                        .HasColumnType("text");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "ParticipantId", "MinuteMark");

                    b.HasIndex("MinuteMark", "MatchId");

                    b.ToTable("MatchParticipantTimelineSnapshots");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchTeamObjective", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("BaronFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("BaronKills")
                        .HasColumnType("integer");

                    b.Property<bool>("DragonFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("DragonKills")
                        .HasColumnType("integer");

                    b.Property<bool>("FirstBlood")
                        .HasColumnType("boolean");

                    b.Property<bool>("HordeFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("HordeKills")
                        .HasColumnType("integer");

                    b.Property<bool>("InhibitorFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("InhibitorKills")
                        .HasColumnType("integer");

                    b.Property<bool>("RiftHeraldFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("RiftHeraldKills")
                        .HasColumnType("integer");

                    b.Property<bool>("TowerFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("TowerKills")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "TeamId");

                    b.ToTable("MatchTeamObjectives");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchTimelineFetchState", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SourcePatch")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("MatchId");

                    b.HasIndex("LastAttemptAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("MatchTimelineFetchStates");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.ItemVersion", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("BuildsFrom")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("'{}'::integer[]");

                    b.PrimitiveCollection<List<int>>("BuildsInto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("'{}'::integer[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InStore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("ItemId", "PatchVersion");

                    b.HasIndex("PatchVersion");

                    b.ToTable("ItemVersions");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.Patch", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Version");

                    b.ToTable("Patches");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.RuneVersion", b =>
                {
                    b.Property<int>("RuneId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RunePathId")
                        .HasColumnType("integer");

                    b.Property<string>("RunePathName")
                        .HasColumnType("text");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("RuneId", "PatchVersion");

                    b.HasIndex("PatchVersion");

                    b.ToTable("RuneVersions");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentChampionLoadout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CurrentChampionLoadouts");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentDataParameters", b =>
                {
                    b.Property<Guid>("CurrentDataParametersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CurrentDataParametersId");

                    b.ToTable("CurrentDataParameters");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.Helpers.UnitWinPercent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CurrentChampionLoadoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfGames")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("WinRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CurrentChampionLoadoutId");

                    b.ToTable("UnitWinPercent");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.RefreshLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("LockedUntilUtc");

                    b.ToTable("RefreshLocks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Account.TftHistoricalRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId");

                    b.ToTable("TftHistoricalRanks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Account.TftRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId", "QueueType")
                        .IsUnique();

                    b.ToTable("TftRanks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Account.TftSummoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<string>("GameNameNormalized")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RevisionDate")
                        .HasColumnType("bigint");

                    b.Property<string>("RiotSummonerId")
                        .HasColumnType("text");

                    b.Property<long>("SummonerLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.Property<string>("TagLineNormalized")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.HasIndex("PlatformRegion", "GameNameNormalized", "TagLineNormalized")
                        .IsUnique();

                    b.ToTable("TftSummoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Account.TftSummonerIngestionCursor", b =>
                {
                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<long?>("BackfillBeforeEpochSeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("ConsecutiveNoopRuns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("SummonerId", "Scope");

                    b.ToTable("TftSummonerIngestionCursors");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameVariation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("MatchDate")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueueId")
                        .HasColumnType("text");

                    b.Property<string>("SetCoreName")
                        .HasColumnType("text");

                    b.Property<int?>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TftGameType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("SetNumber");

                    b.HasIndex("PlatformRegion", "Patch", "SetNumber", "Status");

                    b.ToTable("TftMatches");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Augments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<int?>("CompanionItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanionSkinId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanionSpecies")
                        .HasColumnType("text");

                    b.Property<int>("GoldLeft")
                        .HasColumnType("integer");

                    b.Property<int>("LastRound")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Placement")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersEliminated")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiotIdGameName")
                        .HasColumnType("text");

                    b.Property<string>("RiotIdTagLine")
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<float>("TimeEliminatedSeconds")
                        .HasColumnType("real");

                    b.Property<int>("TotalDamageToPlayers")
                        .HasColumnType("integer");

                    b.Property<bool?>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Placement");

                    b.HasIndex("MatchId", "SummonerId")
                        .IsUnique();

                    b.HasIndex("SummonerId", "Placement");

                    b.ToTable("TftMatchParticipants");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatchParticipantAugment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ApiName", "ParticipantId");

                    b.ToTable("TftMatchParticipantAugments");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatchParticipantTrait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumUnits")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Style")
                        .HasColumnType("integer");

                    b.Property<int>("TierCurrent")
                        .HasColumnType("integer");

                    b.Property<int?>("TierTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParticipantId");

                    b.ToTable("TftMatchParticipantTraits");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatchParticipantUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Chosen")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("ItemNames")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.PrimitiveCollection<int[]>("Items")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("'{}'::integer[]");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("TftMatchParticipantUnits");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Static.TftAugmentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("AssociatedTraits")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("IncompatibleTraits")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<bool>("Unique")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SetNumber", "ApiName")
                        .IsUnique();

                    b.ToTable("TftAugmentVersions");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Static.TftItemVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("AssociatedTraits")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.PrimitiveCollection<string[]>("Composition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("IncompatibleTraits")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RiotItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<bool>("Unique")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SetNumber", "ApiName")
                        .IsUnique();

                    b.ToTable("TftItemVersions");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Static.TftPatch", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<string>("ActiveSetCoreName")
                        .HasColumnType("text");

                    b.Property<int?>("ActiveSetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Version");

                    b.ToTable("TftPatches");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Static.TftSet", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Number"));

                    b.Property<string>("CoreName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Mutator")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Number");

                    b.ToTable("TftSets");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Static.TftTraitVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SetNumber", "ApiName")
                        .IsUnique();

                    b.ToTable("TftTraitVersions");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Static.TftUnitVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SquareIcon")
                        .HasColumnType("text");

                    b.Property<string>("TileIcon")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Traits")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SetNumber", "ApiName")
                        .IsUnique();

                    b.ToTable("TftUnitVersions");
                });

            modelBuilder.Entity("MatchSummoner", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", null)
                        .WithMany()
                        .HasForeignKey("SummonersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserFavoriteSummoner", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Auth.UserAccount", "UserAccount")
                        .WithMany("FavoriteSummoners")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserPreferences", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Auth.UserAccount", "UserAccount")
                        .WithOne("Preferences")
                        .HasForeignKey("Transcendence.Data.Models.Auth.UserPreferences", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserRefreshToken", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Auth.UserAccount", "UserAccount")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserRole", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Auth.UserAccount", "UserAccount")
                        .WithMany("Roles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.ChampionMastery", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("ChampionMasteries")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.HistoricalRank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("HistoricalRanks")
                        .HasForeignKey("SummonerId");

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Rank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("Ranks")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.SummonerIngestionCursor", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("IngestionCursors")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchBan", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("Bans")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipant", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItem", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.MatchParticipant", "MatchParticipant")
                        .WithMany("Items")
                        .HasForeignKey("MatchParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Static.ItemVersion", "ItemVersion")
                        .WithMany()
                        .HasForeignKey("ItemId", "PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemVersion");

                    b.Navigation("MatchParticipant");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItemPurchase", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantRune", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.MatchParticipant", "MatchParticipant")
                        .WithMany("Runes")
                        .HasForeignKey("MatchParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Static.RuneVersion", "RuneVersion")
                        .WithMany()
                        .HasForeignKey("RuneId", "PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchParticipant");

                    b.Navigation("RuneVersion");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantSkillOrder", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantTimelineSnapshot", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("TimelineSnapshots")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchTeamObjective", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("TeamObjectives")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchTimelineFetchState", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithOne("TimelineFetchState")
                        .HasForeignKey("Transcendence.Data.Models.LoL.Match.MatchTimelineFetchState", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.ItemVersion", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Static.Patch", "Patch")
                        .WithMany()
                        .HasForeignKey("PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patch");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.RuneVersion", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Static.Patch", "Patch")
                        .WithMany()
                        .HasForeignKey("PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patch");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.Helpers.UnitWinPercent", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Service.CurrentChampionLoadout", null)
                        .WithMany("UnitWinPercents")
                        .HasForeignKey("CurrentChampionLoadoutId");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Account.TftHistoricalRank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Tft.Account.TftSummoner", "Summoner")
                        .WithMany("HistoricalRanks")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Account.TftRank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Tft.Account.TftSummoner", "Summoner")
                        .WithMany("Ranks")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Account.TftSummonerIngestionCursor", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Tft.Account.TftSummoner", "Summoner")
                        .WithMany("IngestionCursors")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatch", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Tft.Static.TftSet", "Set")
                        .WithMany()
                        .HasForeignKey("SetNumber");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatchParticipant", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Tft.Match.TftMatch", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.Tft.Account.TftSummoner", "Summoner")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatchParticipantAugment", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Tft.Match.TftMatchParticipant", "Participant")
                        .WithMany("AugmentRows")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatchParticipantTrait", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Tft.Match.TftMatchParticipant", "Participant")
                        .WithMany("Traits")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatchParticipantUnit", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Tft.Match.TftMatchParticipant", "Participant")
                        .WithMany("Units")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Auth.UserAccount", b =>
                {
                    b.Navigation("FavoriteSummoners");

                    b.Navigation("Preferences");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Summoner", b =>
                {
                    b.Navigation("ChampionMasteries");

                    b.Navigation("HistoricalRanks");

                    b.Navigation("IngestionCursors");

                    b.Navigation("MatchParticipants");

                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.Match", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Participants");

                    b.Navigation("TeamObjectives");

                    b.Navigation("TimelineFetchState");

                    b.Navigation("TimelineSnapshots");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipant", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Runes");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentChampionLoadout", b =>
                {
                    b.Navigation("UnitWinPercents");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Account.TftSummoner", b =>
                {
                    b.Navigation("HistoricalRanks");

                    b.Navigation("IngestionCursors");

                    b.Navigation("MatchParticipants");

                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatch", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Tft.Match.TftMatchParticipant", b =>
                {
                    b.Navigation("AugmentRows");

                    b.Navigation("Traits");

                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
